import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })
const links = [
  {text: "quiz1", path: "/quiz1"},
  {text: "quiz2", path: "/quiz2"},
  {text: "quiz3", path: "/quiz3"},
]

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar title="mk codelab" links={links} />
        {/* <div className="h-20" /> Placeholder for the fixed navbar */}

        {children}
      </body>
    </html>
  )
}

